# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

f_nums = []

def Fib(i):
    if i == 0:
        return 0
    elif i == 1:
        return 1
    else:
        return Fib(i-1) + Fib(i-2)

for i in range(1, 4000000):
    if Fib(i)%2 == 0:
        f_nums.append(Fib(i))

print(sum(f_nums))
print(f_nums)
